version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - chara
  - eslintcache
  - foxact
  - generouted
  - iconify
  - importantimport
  - kwaa
  - kwaroran
  - libsql
  - masknet
  - moeru
  - moetalk
  - ollama
  - risu
  - roleplay
  - Seraphina
  - sonarjs
  - sqlocal
  - virtua
  - xsai
ignoreWords: []
import: []
