version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - eslintcache
  - foxact
  - iconify
  - importantimport
  - moeru
  - moetalk
  - ollama
  - stylex
  - xsai
ignoreWords: []
import: []
