version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - eslintcache
  - foxact
  - iconify
  - importantimport
  - masknet
  - moeru
  - moetalk
  - ollama
  - sonarjs
  - stylex
  - xsai
ignoreWords: []
import: []
