name: check

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: latest
          registry-url: https://registry.npmjs.org
      - run: |
          git rev-parse HEAD || true
          git status || true
          cat /home/runner/work/talk/talk/src/router.ts
      - run: pnpm install
      - run: pnpm build
      - run: pnpm eslint .
